name: nightly

on:
  schedule:
    # every 10 mins
    - cron: "*/10 * * * *"

jobs:
  checkout:
    # only on the main repository
    if: github.repository == '0xc0170/docker-hub'
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

  sanity-check:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
      - name: Blinky test
        id: blinky_build
        run: ./scripts/blinky_build.sh

  publish-nightly:
    needs: sanity-check
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: user/app:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
